export const actions = {
    ADD_ITEM: 'ADD_ITEM',
    DECREMENT_COUNT_IN_CARD: 'DECREMENT_COUNT_IN_CARD',
    INCREMENT_COUNT_IN_CARD: 'INCREMENT_COUNT_IN_CARD',
    CLOSE_ITEM_CARD: 'CLOSE_ITEM_CARD',
    SET_COUNT_IN_CARD: 'SET_COUNT_IN_CARD',
    ENTER_PROMO: 'ENTER_PROMO',
    APPLY_PROMO: 'APPLY_PROMO',
    DELETE_PROMO: 'DELETE_PROMO',
    MOVE_TO_BASKET: 'MOVE_TO_BASKET',
    OPEN_BASKET: 'OPEN_BASKET',
    CLOSE_BASKET: 'CLOSE_BASKET',
    DECREMENT_COUNT_IN_BASKET: 'DECREMENT_COUNT_IN_BASKET',
    INCREMENT_COUNT_IN_BASKET: 'INCREMENT_COUNT_IN_BASKET',
    SET_COUNT_IN_BASKET: 'SET_COUNT_IN_BASKET',
    ENTER_PROMO_IN_BASKET: 'ENTER_PROMO_IN_BASKET',
    APPLY_PROMO_IN_BASKET: 'APPLY_PROMO_IN_BASKET',
    DELETE_PROMO_IN_BASKET: 'DELETE_PROMO_IN_BASKET',
    DELETE_ITEM: 'DELETE_ITEM',
    ENTER_PROMO_ALL: 'ENTER_PROMO_ALL',
    APPLY_PROMO_ALL: 'APPLY_PROMO_ALL',
    DELETE_PROMO_ALL: 'DELETE_PROMO_ALL',
};

export const promo = {
    'Confirmit': 10,
    'Frontend': 25
};